### ISSUE TITLE
GUI sql section title 

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/pgRoutingLayer#101]
In the pgRouting documentation it says "inner query".
For example: https://docs.pgrouting.org/dev/en/pgr_dijkstra.html#inner-query
What should it be:
- `Inner SQL` 
- `SQL` in uppercase 
- `sql` in lowercase currently used in the GUI 
![innersql](https://user-images.githubusercontent.com/39493413/49532723-caffd180-f882-11e8-8d5c-f32f3da18354.png)

**Comment by cvvergara** [comment]
I think "sql" in lowercase is incorrect

My preference is `Inner SQL` to match the documentation

**Comment by MarPetra** [comment]
Thank you, I'll do it

**Comment by cvvergara** [comment]
Wait until we hear more comments about it

**Comment by cayetanobv** [comment]
@MarPetra @cvvergara I prefer SQL in upper case.

**Comment by dkastl** [comment]
Wouldn't it better to make this a bit more explanative?
Name it `SQL` or `sql`, this is both really short and doesn't say much. `Inner SQL` is maybe just understandable for people like us.

What about giving it a meaningful title like `Function SQL Parameters`? Better suggestions welcome, but looking at the screenshot we should have enough space to make this title a bit longer.

**Comment by dkastl** [comment]
Other idea: can we add some information/help to that GUI? Maybe with tooltips or an expandable description, a link to the documentation or something else.

**Comment by cvvergara** [comment]
Just a clarification:
```
SELECT * from pgr_dijkstra(
    'SELECT  id, source, target, cost, reverse_cost FROM edge_table', --(1)
    25, --(2)
    32)   --(3)
``` 
pgr_dijkstra(one to one) function has 3 parameters:
1. The inner SQL
2. The source
3. The target

The inner SQL has 5 columns
 id, source, target, cost, reverse_cost

**Comment by cvvergara** [comment]
@MarPetra 
Change it to upper case
sql -> SQL
