### ISSUE TITLE
add some information/help

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgRoutingLayer#103]
From @dkastl 
https://github.com/pgRouting/pgRoutingLayer/issues/101#issuecomment-444887129
Maybe with tooltips or an expandable description, a link to the documentation or something else.

**Comment by cvvergara** [comment]
@cayetanobv 

Any ideas on how to do it?

**Comment by cayetanobv** [comment]
Tooltips are easy to include in QGIS GUI. First, we should decide where to put tooltips (labels, text boxes, buttons, etc.). Also we can add a Help button to link with docs.

**Comment by cvvergara** [comment]
well, 
adding the the link button, in my mind, seems faster.
maybe just like the one in QGIS
maybe can look like this:

![image](https://user-images.githubusercontent.com/5035290/49705169-45618600-fbe2-11e8-88f9-ca94de410e96.png)![image](https://user-images.githubusercontent.com/5035290/49705192-76da5180-fbe2-11e8-9163-9fec89e9e384.png)

**Comment by dkastl** [comment]
I didn't want to make everyone lots of additional work, I was just trying to understand, what a QGIS pgRouting plugin user looks like. And I guess, that many of them are not familiar with SQL or just a little.

So right now the plugin helps to "fill in" the SQL query parameters, but if someone doesn't understand SQL, then lots of the form names as they are are might be not understandable for them. 

My suggestion with tooltips is, that we can give a little more information about each item, and by linking to the documentation for example, we can make it easy for users to find more information. 

For a next version of the plugin I could even think of a different approach, where either the users gets a better understanding, that they actually build some SQL query, or the opposite, try to not even provide a UI that resembles a "query builder".

For now I would suggest to make as easy additions as possible, but provide a little more explanations to the user with the tools QGIS provides.

**Comment by cvvergara** [comment]
Tool tips and link to pgRouting documentation were added, closing
