### ISSUE TITLE
Bad use of query parameters in psycopg2

### ISSUE THREAD

**Issue by cayetanobv** [pgRouting/pgRoutingLayer#105]
This issue affects to all SQL queries in plugin. Related doc: http://initd.org/psycopg/docs/usage.html#the-problem-with-the-query-parameters

**Comment by cvvergara** [comment]
I am trying to fix this one
https://github.com/cvvergara/pgRoutingLayer/pull/2

**Comment by cayetanobv** [comment]
Hi @cvvergara . This is not the way to fix SQL injection problem with psycopg2. You are changing Python old way for string formatting by a new way (using ```format``` method) leaving the problem exactly in the same point. 

The way to fix this problem needs several steps (maybe could be more steps so more analysis is needed because the code is not very clean at this point):

1. We need to fix SQL executors in pgRoutingLayer.y module using correcly the second argument of ```execute``` method to correctly send the query parameters to PostgreSQL (We should wrap SQL executor in a method to avoid this mess of independent calls): 
  - https://github.com/pgRouting/pgRoutingLayer/blob/master/pgRoutingLayer.py#L619
  - https://github.com/pgRouting/pgRoutingLayer/blob/master/pgRoutingLayer.py#L1250
  - https://github.com/pgRouting/pgRoutingLayer/blob/master/pgRoutingLayer.py#L1124
  - https://github.com/pgRouting/pgRoutingLayer/blob/master/pgRoutingLayer.py#L1148

2. There are dozens of direct calls to execute method (mainly from functions to export or render results but not from main calls to pgRouting) from almost all functions modules. This is a mess :( We need to wrap this calls from a common method located in pgRoutingLayer.py module or in postgis.py module. 

3.  Fix SQL executor private method (```_exec_sql```) in postgis.py module using correcly the second argument of ```execute``` method to correctly send the query parameters to PostgreSQL: https://github.com/pgRouting/pgRoutingLayer/blob/master/connectors/postgis.py#L791

4. Review and fix all calls to executor private method inside ```postgis.py``` module.  

5. A very important step: Find and fix all SQL builders that exists in the plugin (there are a lot of queries and the methods are not always coded in the same way). We need to remove string parameters interpolation in all queries and return arguments totally independent from SQL.

This is a hard work that we need to do very carefully to avoid regressions.

**Comment by cvvergara** [comment]
@cayetanobv we are not having these problems anymore, please reopen if I am wrong
