### ISSUE TITLE
Bounding envelope should be an option not always set

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgRoutingLayer#12]
I didn't check the other functions, but I notice when using drivingDistance, it automatically puts in a bounding box filter. While this is normally the right thing to do, I think there are cases where you don't want a bounding box or at the very least want to be able to control how big the box is.  One that comes to mind is air flight.

So I think it's better to make this a check box option or maybe a function of expand size (or map view).  People might not always have their map view set to full region they want checked, so even going by map view without asking would not always be the right value to use.

**Comment by cvvergara** [comment]
I'll try to fix in a latter version

**Comment by cvvergara** [comment]
BBOX checkbox was added, Version 3.0.0. has it
Closing
