### ISSUE TITLE
PgRoutingLayer QGIS 3 Repository

### ISSUE THREAD

**Issue by fgianoli** [pgRouting/pgRoutingLayer#121]
Dear, I read that PgRoutingLayer was migrated to QGIS 3.x and on the metadata I read that the QGIS maximum version is 3.99 but I am not able to find it on the QGIS 3 plugin repository (I have enabled experimental plugins). 

![image](https://user-images.githubusercontent.com/28388726/53791564-08c7d100-3f2a-11e9-946a-fb42996650e9.png)

**Comment by cayetanobv** [comment]
Hi @fgianoli , plugin for QGIS 3 is still in pre-release version: https://github.com/pgRouting/pgRoutingLayer/releases
We are planning to release version to upload to QGIS plugin hub very soon (this month).
You can download prerelease from github and use it if you want.
Thanks!

**Comment by cvvergara** [comment]
Hi @fgianoli 
Here is a wiki on how to test it locally
https://github.com/pgRouting/pgRoutingLayer/wiki/How-to:-test-pgRoutingLayer-3

**Comment by fgianoli** [comment]
Thanks, I tried to download the zip from the releases (3.0.0.rc) and to install it in QGIS 3.6 using "install plugin from zip" but the error is this:

Couldn't load plugin 'pgRoutingLayer-3.0.0-rc' 

ModuleNotFoundError: No module named 'pgRoutingLayer-3.0' 
Traceback (most recent call last):
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/QGIS/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pgRoutingLayer-3.0'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, 58734527ab

**Comment by cvvergara** [comment]
Yes, the zip files are not QGIS plugin installable, because we have more files and tools for developing than what QGIS expects

**Comment by cayetanobv** [comment]
@fgianoli @cvvergara The fail is because you download from Gihub a ZIP compressed folder with this name "pgRoutingLayer-3.0" but QGIS try to find "pgRoutingLayer" folder (name given in metadata). To solve this problem you can rename folder to pgRoutingLaye and copy in plugin folder directly.

**Comment by fgianoli** [comment]
Thanks @cayetanobv  I have installed the plugin and it is amazing.
Thanks for developing this tool!

**Comment by cayetanobv** [comment]
Thanks to you for using it. You are always welcome to PgRouting community!
