### ISSUE TITLE
pgRouting plugin error

### ISSUE THREAD

**Issue by alloylo** [pgRouting/pgRoutingLayer#125]
I have used osm2po to create routing data after load the data to database(postgresql) then from it to QGis.when using the pgrouting plugin the error appears:
 2019-05-16T12:43:17 WARNING Traceback (most recent call last): File "C:/Users/Alloylo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 505, in setSourceIds vertexMarker.setCenter(geom.asPoint()) ValueError: Null geometry cannot be converted to a point.
![pgerror](https://user-images.githubusercontent.com/37999349/57850054-445e0180-77dd-11e9-971b-1166a6135cca.png)

**Comment by cayetanobv** [comment]
Hi @alloylo . You have NULL geometries in geom_way field. You need to build the graph in a correct way. You can either apply topology creation directly from pgRouting (http://docs.pgrouting.org/latest/en/topology-functions.html#topology-functions) or import your data using osm2pgrouting (https://github.com/pgRouting/osm2pgrouting). 

Anyway we have to control better this kind od topology errors.

Thanks for your report!

**Comment by alloylo** [comment]
Thanks @cayetanobv  for your fast reply ,but i have import the data to database using osm2po and the geom_way field is full of data 
![image](https://user-images.githubusercontent.com/37999349/57851334-93f1fc80-77e0-11e9-9757-28c9cc82662d.png)

**Comment by cayetanobv** [comment]
This screenshot is about edges table. But... how did you build topology? Do you have a vertices table? You need a vertices table to work with pgRouting.

**Comment by alloylo** [comment]
I have created the table of vertices should i join the table of edge and the table of vertices in on table

**Comment by cayetanobv** [comment]
Hi @alloylo ,

To use pgRouting you need to have at least two tables, edges and vertices. You don't need to do joins between tables, but if the name of geometry columns are different or the name of other columns are not the default, you need to handle it in SQL queries. You can learn how it works here: http://docs.pgrouting.org/latest/en/pgr_createTopology.html#usage-when-the-edge-table-s-columns-do-not-match-the-default-values

Review how topology is created here: http://docs.pgrouting.org/latest/en/pgr_createTopology.html#pgr-create-topology  

More: you can improve your understanding of pgRouting concepts reviewing the open workshops: https://workshop.pgrouting.org/

Thanks,

**Comment by mvvthdp** [comment]
Best regards, my problem, once loaded the 2 tables and the selection of the databases in the complement, the formula selector has no formulas, can you help me?

**Comment by WilliamWalker** [comment]
I am having the same trouble.  I have loaded my edges into postgresql, and generated the vertices table.  I connect to my database, and can select it in the pgRouting Layer dockable window.  However, the pgr_f() combobox contains no values.

**Comment by cayetanobv** [comment]
Hi @WilliamWalker ,

Some questions for you about versions you are using:
  - pgRouting version.
  - QGIS version.
  - OS (Linux, Mac, Windows).

Thanks,

**Comment by WilliamWalker** [comment]
pgRouting 2.0 (postgresql 9.4, postgis 2.1.8)
QGIS 3.12
Windows 10

**Comment by cayetanobv** [comment]
Hi @WilliamWalker ,

Sorry for my late response but I was very busy last week. You are using a very old version of pgRouting (pgRouting 2.0 was released in 2014). You need to upgrade to 2.6 version to use this plugin. On the other hand, Postgres 9.4 is a non supported version by Postgresql project (https://www.postgresql.org/support/versioning/). You should upgrade your PostgreSQL version. PostGIS version you are using is too old and non supported by new Postgres versions: https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS

Upgrade all your versions and test again if this plugin works with your dataset.

Thanks,

**Comment by cvvergara** [comment]
Will close the issue as it is related to an old version of the plugin
