### ISSUE TITLE
drivingDistance and dijkstra export do not work

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgRoutingLayer#13]
Export gives an error

I'll pull the latest to confirm I have the latest.  Close this out if you know already fixed.

usin https://github.com/pgRouting/pgRoutingLayer/tree/vdev/pgr-2.1.0

Preview worked, but then when I went to go to export, I get this error:

```
relation "edge_table" does not exist
LINE 3: FROM edg_table
```

I think this may be a problem with export in general.  I tried several permuations of dijkstra as well and got the same error.  It used to work before though so not sure what changed.

**Comment by cvvergara** [comment]
Fixed on develop
