### ISSUE TITLE
Allow export alphashape and driving distance

### ISSUE THREAD

**Issue by hebertazevedo** [pgRouting/pgRoutingLayer#14]
Dear Colegues,

do you have any expectation to add the export function in driving distance and alphashape algoritim .

**Comment by dkastl** [comment]
What do you exactly mean with "export function"?

**Comment by robe2** [comment]
It's in the beta, but last I tried it's broken.  I complained about it 
at https://github.com/pgRouting/pgRoutingLayer/issues/13

**Comment by cvvergara** [comment]
sorry, being focused on preparing what its going to be used for GSOC, I'll
see about it next week
Vicky

On Mon, May 16, 2016 at 10:02 PM, Regina Obe <notifications@github.com>
wrote:

> It's in the beta, but last I tried it's broken. I complained about it
> at #13 <https://github.com/pgRouting/pgRoutingLayer/issues/13>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pgRouting/pgRoutingLayer/issues/14#issuecomment-219607787>
>



-- 

Georepublic UG (haftungsbeschränkt)
Salzmannstraße 44,
81739 München, Germany

Vicky Vergara
Operations Research

eMail: vicky@georepublic.de
Web: https://georepublic.info

Tel: +49 (089) 4161 7698-1
Fax: +49 (089) 4161 7698-9

Commercial register: Amtsgericht München, HRB 181428
CEO: Daniel Kastl

**Comment by hebertazevedo** [comment]
Colleagues,

thanks for the awnsers. Daniel, i am refering to the button export is not enabled when using driving distance and alpha shape. Vicky, grateful for the efforts in development this tool. I'm expecting  for future versions.

Best regards

**Comment by sanak** [comment]
@cvvergara 
I supported it once during v2.1 development, but did you remove it ?
https://github.com/sanak/pgRoutingLayer/issues/2

@hebertazevedo 
Which pgRoutingLayer plugin version are you using ?

**Comment by hebertazevedo** [comment]
sanak - It's the 2.0.0

**Comment by sanak** [comment]
@hebertazevedo 
Okay, then it still doesn't support the functionality.
The development version includes the functionality,
so, please wait for a new release.

**Comment by cvvergara** [comment]
Fixed in develop
@hebertazevedo I am in the releasing process of v2.1.0, so soon you can try again.
