### ISSUE TITLE
Alphashape report another error

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#18]
When I tried "alphashape" function with FOSS4G 2013 Nottingham pgRouting Workshop example,
I got the following error.
![alphashape_error](https://cloud.githubusercontent.com/assets/629923/16660580/f112c2cc-44a9-11e6-922c-f19af2fc37ff.png)

**Comment by cvvergara** [comment]
in you databse do you have:
ways_vertices_pgr?

A graph is defined by its edges and vertices, in this case if the edges are in **ways** then the vertices are in **ways_vertices_pgr**

**Comment by sanak** [comment]
Thanks for information.
After creating **ways_vertices_pgr** table by executing `pgr_createVerticesTable` function,
there was no problem.
http://docs.pgrouting.org/2.0/en/src/common/doc/functions/create_vert_table.html#pgr-create-vert-table
