### ISSUE TITLE
"pgr_astar" and "pgr_bdAstar" are called from another (opposite) functions

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#22]
"pgr_bdAstar" is called from "astar" function.
https://github.com/pgRouting/pgRoutingLayer/blob/develop/functions/astar.py#L38

Vice versa, "pgr_astar" is called from "bdAstar" function.
https://github.com/pgRouting/pgRoutingLayer/blob/develop/functions/bdAstar.py#L38

**Comment by cvvergara** [comment]
Fixed on develop

**Comment by sanak** [comment]
I confirmed that it is fixed.
Thanks!
