### ISSUE TITLE
Optimize GUI on HiDPI displays

### ISSUE THREAD

**Issue by anitagraser** [pgRouting/pgRoutingLayer#29]
Currently, there's always a scrollbar in the SQL section, even if there would be enough space for the dock contents overall:

![pgroutinglayer](https://cloud.githubusercontent.com/assets/590385/17031853/9cd7001a-4f76-11e6-921b-5cfd76258349.PNG)

**Comment by anitagraser** [comment]
Here's my suggestion: https://dl.dropboxusercontent.com/u/42637169/ui_pgRoutingLayer.ui

![pgroutinglayer2](https://cloud.githubusercontent.com/assets/590385/17035475/b16a6132-4f87-11e6-8e34-46182fde59ed.PNG)

**Comment by sanak** [comment]
Okay, thanks for your report and suggestion.
The reason of separating "sql" and "Arguments" was that I wanted to show "Arguments" in any height,
but the current layout/spacing which I modified is too bad, actually...
I will check it in this weekend.

**Comment by cvvergara** [comment]
Thanks for reviewing

**Comment by sanak** [comment]
@anitagraser 
On "feature/optimize_gui_by_splitter" branch, I added a splitter between "sql" and
"Arguments" group box, then wrote each ratio adjusting logic
when changing "Function" combo box selection.
![splitter](https://cloud.githubusercontent.com/assets/629923/17101356/062defac-52af-11e6-964d-8a9fa9dbd827.png)

I will try to merge your layout (spacing, alignment, etc) adjustment on the branch, later (at the next weekend).
