### ISSUE TITLE
Support v2.1 new signature (pgr_dijkstra/pgr_ksp/pgr_drivingDistance)

### ISSUE THREAD

**Issue by sanak** [pgRouting/pgRoutingLayer#3]
Create new function (*.py) files (dijkstra_v3.py .etc) for v3 signature.

**Comment by cvvergara** [comment]
@sanak 
FYI ksp: 
The minimal signature:
```
pgr_ksp(TEXT sql_q, BIGINT start_vid, BIGINT end_vid, INTEGER k);
  RETURNS SET OF (seq, path_id, path_seq, node, edge, cost, agg_cost) or EMPTY SET
```
The full signature:
```
pgr_ksp(TEXT edges_sql, BIGINT start_vid, BIGINT end_vid, INTEGER k,
      BOOLEAN directed:=true, BOOLEAN heap_paths:=false);
  RETURNS SET OF (seq, path_id, path_seq, node, edge, cost, agg_cost) or EMPTY SET
```

**Comment by cvvergara** [comment]
Loading some images for the wiki

![u astar 2 to 3 bbox -0 3 -0 12 4 3 4 12](https://cloud.githubusercontent.com/assets/5035290/14548648/6acffd6e-027e-11e6-834a-fc5faa611c21.jpg)
![d dijkstra 2 3 to 2 3 11 bbox -0 3 -0 12 4 3 4 12](https://cloud.githubusercontent.com/assets/5035290/14548649/6ae8184a-027e-11e6-9b86-7b1c3aafdf4c.jpg)
![md dijkstra 2 3 to 2 3 11 bbox -0 3 -0 12 4 3 4 12](https://cloud.githubusercontent.com/assets/5035290/14548650/6b07d810-027e-11e6-88f3-cccfc9007f09.jpg)

**Comment by cvvergara** [comment]
loading more images for the wiki
![astar20](https://cloud.githubusercontent.com/assets/5035290/18722838/d1ef2be6-7ffb-11e6-8d5c-d226f4e58d28.png)
![astar23](https://cloud.githubusercontent.com/assets/5035290/18722841/d4cd82ea-7ffb-11e6-8a1d-6dfc9330a406.png)
