### ISSUE TITLE
Error on plugin activation

### ISSUE THREAD

**Issue by fuzzysolutions** [pgRouting/pgRoutingLayer#39]
I get an "unable to convert a QVariant of type 0 to a QMetaType of type 10" error window as soon as I try activating the plugin after install. See full message below. While that, I see the pgrouting Dockwidget in the bottom left corner of my QGIS window, but it disappears after accepting the error message.

> TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/jludwig/.qgis2/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 210, in initGui
    self.loadSettings()
  File "C:/Users/jludwig/.qgis2/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 1207, in loadSettings
    idx = self.dock.comboConnections.findText(settings.value('/pgRoutingLayer/Database', type=str))
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10

> Python-Version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS-Version: 2.18.13 Las Palmas, 8cba0bb9eb 

> Python-Pfad:
C:/OSGEO4~1/apps/qgis/./python/plugins\processing
C:/OSGEO4~1/apps/qgis/./python
C:/Users/jludwig/.qgis2/python
C:/Users/jludwig/.qgis2/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\bin\python27.zip
C:\OSGEO4~1\apps\Python27\DLLs
C:\OSGEO4~1\apps\Python27\lib
C:\OSGEO4~1\apps\Python27\lib\plat-win
C:\OSGEO4~1\apps\Python27\lib\lib-tk
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python27
C:\OSGEO4~1\apps\Python27\lib\site-packages
C:\OSGEO4~1\apps\Python27\lib\site-packages\setuptools-28.8.0-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\pip-9.0.1-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32
C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin
C:\OSGEO4~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\OSGEO4~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/jludwig/.qgis2//python

**Comment by thiefjim** [comment]
I have same issue
```
Couldn't load plugin pgRoutingLayer due to an error when calling its initGui() method 

TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10 
Traceback (most recent call last):
  File "d:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/thiefjim/.qgis2/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 210, in initGui
    self.loadSettings()
  File "C:/Users/thiefjim/.qgis2/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 1207, in loadSettings
    idx = self.dock.comboConnections.findText(settings.value('/pgRoutingLayer/Database', type=str))
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 10


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.13 Las Palmas, 8cba0bb9eb 

Python Path:
d:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\processing
d:/PROGRA~2/QGIS2~1.18/apps/qgis/./python
C:/Users/thiefjim/.qgis2/python
C:/Users/thiefjim/.qgis2/python/plugins
d:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins
d:\SUMO\tools
d:\PROGRA~2\QGIS2~1.18\bin\python27.zip
d:\PROGRA~2\QGIS2~1.18\apps\Python27\DLLs
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\plat-win
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\lib-tk
d:\PROGRA~2\QGIS2~1.18\bin
d:\PROGRA~2\QGIS2~1.18\apps\Python27
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\win32
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
d:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/thiefjim/.qgis2//python
```

**Comment by sanak** [comment]
I encountered above issue when I delete `/pgRoutingLayer/Database` key itself from Windows registry editor (regedit).
And I confirmed that reverting the following last commit's line 1207 solved the issue.
https://github.com/pgRouting/pgRoutingLayer/commit/fb232f4464ffe611da91359108e29ab1a85a1da8#diff-6e6a5272928927845bfac41e4e2d3f90L1207
```diff
-        idx = self.dock.comboConnections.findText(settings.value('/pgRoutingLayer/Database', type=str))
+        idx = self.dock.comboConnections.findText(Utils.getStringValue(settings, '/pgRoutingLayer/Database', ''))
```

**Comment by cvvergara** [comment]
Done
