### ISSUE TITLE
Error loading DB

### ISSUE THREAD

**Issue by pwerspire** [pgRouting/pgRoutingLayer#46]
Hi,

I can't select database in the drop down menu of the plugin and when I do refresh I have this error:

2018-03-08T22:00:31	0	dbname:LisbonGis, definition of service "NULL" not found

I'm using version 2.18.15 on mac os.

Can you help?

**Comment by dkastl** [comment]
Can you make sure, that you can view your database layers in QGIS using this database connection?

**Comment by pwerspire** [comment]
Hi,
Yes I can see it. I also added to canvas from there, so it's working the connection

**Comment by cvvergara** [comment]
we dont have a 2.18 version of pgroutingLayer

**Comment by cayetanobv** [comment]
Hi @pwerspire ,

Do you have pgRouting extension created in your PostgreSQL database? You can't use the plugin if you don't have this extension loaded in the database you want to use with pgRoutingLayer.  It does not matter if you have created the pgRouting network topology in your database (i.e. with osm2pgrouting), you need to explicitly create the extension.

Thanks,

**Comment by cvvergara** [comment]
Problem was fixed locally by user
