### ISSUE TITLE
Community Bonding Period : Activities to be done .

### ISSUE THREAD

**Issue by AasheeshT** [pgRouting/pgRoutingLayer#48]
# **Community Bonding Period Tasks**
![img_2765](https://user-images.githubusercontent.com/6928365/39673585-ba2fce96-515c-11e8-9ed4-9ca96b2dec0f.JPG)

![img_2764](https://user-images.githubusercontent.com/6928365/39673542-2aa8f982-515c-11e8-968a-83f7d973575e.JPG)

**Comment by cvvergara** [comment]
This was to be done on your fork's issues

**Comment by cvvergara** [comment]
@AasheeshT you need to set up issues on your fork
