### ISSUE TITLE
Error on drivingdistance Function

### ISSUE THREAD

**Issue by faizalprbw** [pgRouting/pgRoutingLayer#49]
i tried to do drivingdistance analysis function and returned this error
`relation A << at_2po_4pgr_vertices A >> is exists, LINE 3: FROM at_2po_4pgr_vertices_pgr`

Here is my data : https://drive.google.com/open?id=1H0LhI_1vU--ztqHUEv4lAi_IhlSE4sS5
It's an osm data that i store into PostgreSQL databases using osm2po (5.2.43)

I'm sure that the geometry field and table name is correct because another function works fine.
I can't figure out whats the problem, the databases privilege is set to All.

I'm using QGIS 2.18.12, PostgreSQL 9.6 with PostGIS 2.4.4 ,and pgRouting 2.6.0

**Comment by cvvergara** [comment]
Do you have at_2po_4pgr_vertices table?

**Comment by cvvergara** [comment]
A graph consists of a set of Edges and a set of vertices, and I am not sure that osm2po generates the vertices table

**Comment by cvvergara** [comment]
pgRouting has (almost) nothing to do with geometries, you do that with postGIS
why dont you try to use osm2pgrouting to import your data to the database

**Comment by cvvergara** [comment]
Version 3.0.0 does not have pgr_drivingDistance yet, and problem indicates that the vertex table was missing, so closing as this "as problem" is not valid anymore.
