### ISSUE TITLE
Manage Milestones & Releases

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgRoutingLayer#8]
Does it make sense to also manage milestones and releases for pgRoutingLayer? I would say "yes".
In that case, should we synchronize releases with pgRouting?

**Comment by dkastl** [comment]
There is a 2.0.0 release tag in the QGIS Plugin Repository. The plugin points to Anita's Github repository:
https://plugins.qgis.org/plugins/pgRoutingLayer/

**Comment by anitagraser** [comment]
Repo info is read from the published plugin's metadata file. I already updated it here to point to the pgrouting repo.

Not sure about synchronizing with pgrouting but it probably won't hurt.

**Comment by cvvergara** [comment]
@dkastl 
So, Master at this moment contains the pgroutingLayer for 2.0.
I shall make a tag, and a release in github, for that one.
Then merge the changes I made for the 2.1, and modify the metadata,
make a release, for the 2.1 changes.
An publish in the plugins.ggis.org. 


Something like that you want?

**Comment by dkastl** [comment]
I didn't think in detail about how to make new plugin releases. I'm not so familiar with how QGIS plugins are released actually. This is not a playground, so we shouldn't try out things without being sure, that it works. 

Do you know, when a new release gets published on plugins.ggis.org? Does it happen, when you change the `metadata.txt` file? The `metadata.txt` file already seems to be upgraded to 2.1.

Otherwise using tags and turn them into releases is a good idea. I'm not sure, if QGIS plugins can have both: `stable` and  ` experimental`, so users can pick the one, they like.

**Comment by dkastl** [comment]
Probably it would be best to use the same version numbers for the plugin as we use for pgRouting ... easier for us ;-)

**Comment by dkastl** [comment]
- [ ] Create Milestones
- [ ] Create Tags
- [ ] Create Releases

**Comment by cvvergara** [comment]
I would not like the "stable" in the plug in, because some of the functions it has, like astar, are not working properly yet in pgRouting.

**Comment by dkastl** [comment]
Well, it's tagged as `experimental` plugin anyway. Just thought, what to do, if there is stable and unstable. Different repositories for example? However, just loud thinking.

**Comment by cvvergara** [comment]
Yeah, we aare new at this

**Comment by anitagraser** [comment]
A plugin is published when you upload the zipped plugin code to plugins.QGIS.org. This is usually done manually.

Afaik there is no good mechanism in place to provide both an experimental and a stable version under the same name because users can only enable the "allow experimental plugins" option globally.

**Comment by dkastl** [comment]
I see. Thanks!
So we can't accidentally break a plugin by just making a change in the repository. Sometimes manually is better ;-)

**Comment by cvvergara** [comment]
I tagged https://github.com/pgRouting/pgRoutingLayer/releases/tag/pgRoutingLayer-2.0.0
I'll set this issue to milestone to 2.0.0 and close issue and close milestone 2.0.0
