### ISSUE TITLE
Create static website

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgRoutingLayer#85]
As described in https://github.com/pgRouting/admin/pull/26#event-1988262325 let's create a static website for the pgRouting QGIS plugin under `qgis.pgrouting.org`.

- [x] DNS settings for subdomain
- [x] Create branch or directory for Github Pages: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/
- [x] Create `CNAME` file as in https://github.com/pgRouting/workshop/blob/gh-pages/CNAME

**Comment by cayetanobv** [comment]
Yesterday I was working a bit in pgRoutingLayer docs. In my own branch I upload last changes:
https://cayetanobv.github.io/pgRoutingLayer/

I'm going to create this branch gh-pages in main repository and add markdown files to docs folder.

I hope to have a completed first version of pgRoutingLayer docs soon. It is a hard work :)

**Comment by cayetanobv** [comment]
Docs are already at https://qgis.pgrouting.org/

**Comment by dkastl** [comment]
Cool!
