### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by dkastl** [pgRouting/pgRoutingLayer#95]
Shouldn't we have a license file in the repository root?

**Comment by cayetanobv** [comment]
Yes, I'm totally agree. GNU GPL (same as QGIS and pgRouting)?

**Comment by dkastl** [comment]
I would say yes.

**Comment by cvvergara** [comment]
We have a [LICENSE](https://github.com/pgRouting/pgRoutingLayer/blob/master/LICENSE) file
Closing
